# Generated by Django 6.1 on 2026-09-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puller_code', models.CharField(max_length=50, unique=True)),
                ('puller_name', models.CharField(max_length=200)),
                ('puller_details', models.TextField(blank=True)),
                ('puller_size', models.CharField(blank=True, max_length=100)),
                ('puller_dimension', models.CharField(blank=True, max_length=100)),
                ('puller_picture', models.ImageField(blank=True, null=True, upload_to='pullers/')),
                ('puller_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('puller_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
