# Generated by Django 6.1 on 2026-09-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puller',
            old_name='puller_dimension',
            new_name='puller_inner_dia',
        ),
        migrations.RemoveField(
            model_name='puller',
            name='puller_picture',
        ),
        migrations.AddField(
            model_name='puller',
            name='puller_length',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='puller',
            name='puller_outer_dia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='puller',
            name='puller_thickness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='puller',
            name='puller_width',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='puller',
            name='puller_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='puller',
            name='puller_weight',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
