# Generated by Django 6.1 on 2026-09-02 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullers', '0002_rename_puller_dimension_puller_puller_inner_dia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pullers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('puller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pullers.puller')),
            ],
        ),
    ]
