# Generated by Django 6.1 on 2026-09-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullers', '0003_pullerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_code', models.CharField(max_length=50, unique=True)),
                ('body_name', models.CharField(max_length=200)),
                ('body_size', models.CharField(blank=True, max_length=100)),
                ('body_weight', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('body_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='puller',
            name='body_parts',
            field=models.ManyToManyField(blank=True, related_name='pullers', to='pullers.bodyparts'),
        ),
    ]
