# Generated by Django 6.1 on 2026-09-09 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullers', '0004_bodyparts_puller_body_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('special', 'Special Puller'), ('regular', 'Regular Puller'), ('da', 'DA Puller'), ('dalh', 'DALH Puller')], max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='puller',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pullers', to='pullers.pullercategory'),
        ),
    ]
